# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- binary: skeema
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Mac
    linux: Linux
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
git:
  short_hash: true
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage:  http://skeema.net
  description: Schema management CLI for MySQL
  maintainer: Evan Elias <evan@skeema.net>
  license: Apache 2.0
  vendor: Skeema LLC
  formats:
  - deb
  - rpm
  